In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.1.1


### 1 | Print the numpy version and the configuration

In [4]:
print(np.__version__)

2.1.1


### 2 | Create a null vector of size 10

In [5]:
v = np.zeros(10 , dtype = int)
print(v)

[0 0 0 0 0 0 0 0 0 0]


### 3| Create a null vector of size 10 but the fifth value which is 1

In [6]:
v = np.zeros(10 , dtype = int)
v[4] = 1
print(v)

[0 0 0 0 1 0 0 0 0 0]


### 4 | Create a vector with values ranging from 10 to 49

In [7]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 5 | Reverse a vector (first element becomes last)

In [8]:
v = np.arange(50)
v = v[::-1]
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 5 | Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
m =np.arange(9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 6 | Find indices of nonzero elements from [1,2,0,0,4,0]


In [10]:
v = np.nonzero([1,2,0,0,4,0])
print(v)

(array([0, 1, 4]),)


### 7 | Create a 3x3 `identity` matrix

#### ماتریس هویت / Identity Matrix

ماتریس هویت یک ماتریس مربعی است که در آن عناصر قطری برابر با ۱ و بقیه عناصر برابر با ۰ هستند، و در ضرب با هر ماتریس دیگری نتیجه همان ماتریس را می‌دهد.

An identity matrix is a square matrix in which all the diagonal elements are 1 and all other elements are 0. It leaves other matrices unchanged when multiplied by them.


In [11]:
m = np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 8 | Create a 3x3x3 array with random values

In [12]:
m = np.random.randint(0,10,size=(3,3,3))
print(m)

[[[4 2 2]
  [7 3 8]
  [2 6 2]]

 [[5 9 0]
  [1 2 1]
  [5 1 1]]

 [[6 3 3]
  [6 7 5]
  [7 1 6]]]


In [13]:
m = np.random.random(size=(3,3,3))
print(m)

[[[0.89225466 0.48574424 0.14081118]
  [0.87376874 0.53823635 0.5233948 ]
  [0.16981801 0.7048611  0.19306798]]

 [[0.15557787 0.70192197 0.0587055 ]
  [0.44814494 0.73211564 0.47073503]
  [0.55461761 0.99844334 0.6753248 ]]

 [[0.17485364 0.22533802 0.0179433 ]
  [0.39070496 0.44611318 0.70613012]
  [0.11864872 0.77120242 0.44253634]]]


### 9 | Create a 10x10 array with random values and find the minimum and maximum values


In [14]:
m = np.random.random(size=(10,10))
max_value , min_value = np.max(m) , np.min(m)
print(max_value,min_value)

0.9723920607519159 0.012998358596752912


In [15]:
m = np.random.random(size=(10,10))
max_value , min_value = m.max(),m.min()
print(max_value,min_value)

0.9999995196823481 0.018667404247977193


In [16]:
m = np.random.randint(0,5,size=(10,10))
print(m)

[[3 3 0 4 0 2 3 2 2 2]
 [0 4 1 3 1 4 3 1 3 4]
 [3 2 4 0 4 0 0 2 1 1]
 [3 4 1 1 2 0 2 0 2 1]
 [4 4 0 2 2 0 4 1 2 0]
 [2 4 3 3 0 0 0 4 4 0]
 [1 3 3 1 1 3 1 4 0 4]
 [4 1 1 1 2 4 0 0 4 4]
 [3 3 2 3 4 2 1 2 1 4]
 [4 2 1 4 4 2 2 1 2 2]]


### 10 | Create a random vector of size 30 and find the mean value

In [17]:
v = np.random.randint(0,10 , size=(30))
v = v.mean()
print(v)

3.5


### 11 | Create a 2d array with 1 on the border and 0 inside

In [18]:
m = np.ones((10,10),dtype=int)
m[1:-1,1:-1] = 0
print(m)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### 12 | What is the result of the following expression?

In [19]:
m = np.diag(1 + np.arange(4), k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 13 | Create a 8x8 matrix and fill it with a checkerboard pattern

In [20]:
m = np.zeros((8,8),dtype=int)
m[1::2,::2]=1 
m[::2,1::2]=1
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 14 | Create a checkerboard 8x8 matrix using the tile function

In [21]:
m = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 15 | Normalize a 5x5 random matrix

In [22]:
m = np.random.random((5,5))
minValue,maxValue = m.min(),m.max()
normalize = (m-minValue)/(maxValue-minValue)
print(normalize)

[[0.55649359 0.34264647 0.20551965 0.37051634 0.24985915]
 [0.42111328 0.69472045 0.01577309 0.83704886 0.01049972]
 [0.35110179 0.18552607 0.6798241  0.28340217 0.99681107]
 [0.93218446 1.         0.12593105 0.05423142 0.        ]
 [0.50236251 0.67383662 0.70311292 0.85028791 0.18977517]]


### 16 | Create a custom dtype that describes a color as four unisgned bytes (RGBA)

In [23]:
color = np.dtype([("r", np.ubyte, 1),
("g", np.ubyte, 1),
("b", np.ubyte, 1),
("a", np.ubyte, 1)])

### 17 | Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [24]:
m = np.dot(np.ones((5,3),dtype=int),np.ones((3,2),dtype=int))
print(m)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [25]:
np.ones((5,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### 18 | Given a 1D array, negate all elements which are between 3 and 8, in place

In [26]:
m = np.arange(11)
m[(3<m)&(m<=8)] *= -1
print(m)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


### 19 | Create a 5x5 matrix with row values ranging from 0 to 4

In [27]:
Z = np.zeros((5,5),dtype=int)
Z += np.arange(5)
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 20 | Consider a generator function that generates 10 integers and use it to build an array

In [28]:
def generat ():
    for x in range(10):
        yield x
v = np.fromiter(generat(),dtype=int,count=-1)
print(v)

[0 1 2 3 4 5 6 7 8 9]


### 21 | Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [33]:
v = np.linspace(0,1,10 , endpoint=False)[1:]
print(v)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


### 21 | Create a random vector of size 10 and sort it

In [39]:
v = np.random.permutation(10)
v = np.sort(v)
print(v)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
v = np.random.permutation(10)
v = np.sort(v)[::-1]
print(v)

[9 8 7 6 5 4 3 2 1 0]


### 22 | Create a 30-element array of random integers in the range [1, 100]. Then, sum it using a method faster than np.sum() and print the result.

In [44]:
v = np.random.randint(0,100,size=30)
v = np.add.reduce(v)
print(v)

1236


### 23 | Consider two random array A anb B, check if they are equal

In [45]:
a = np.random.randint(0,20,size=30)
b = np.random.randint(0,20,size=30)
print(np.array_equal(a,b))

False


### 24 | Consider two random arrays, A and B, both with floating-point values. Check if they are equal

In [49]:
a = np.random.uniform(0,10,size=20)
b = np.random.uniform(0,10,size=20)
print(np.allclose(a,b))

False


### 25 | Make an array immutable (readonly)

In [54]:
v = np.arange(0,20)
v.flags.writeable = False
# v[0]=1

### 26 | Create random vector of size 10 and replace the maximum value by 0

In [67]:
v = np.random.randint(0,50,size=10)
v[v.argmax()] = 0
print(v)

[32  8 25 24 35 35  5  0 26 30]


### 27 | How to find the closest value (to a given scalar) in an array?

In [74]:
v = np.array([1, 4, 7, 9, 13, 20])
c = 6
z = v[np.abs(v-c).argmin()]
print(z)

7


### 28 | How to convert a float (32 bits) array into an integer (32 bits) in place?

In [75]:
v = np.arange(10, dtype=np.int32)
v = v.astype(np.float32, copy=False)

### 29 | Create a 5x5 2D array of random numbers between 0 and 1. Then, calculate the mean of each row and store it in a new array.

In [77]:
v = np.random.rand(5, 5)
row_means = np.mean(v, axis=1)
print(row_means)

[0.61385415 0.4149201  0.4788975  0.61006708 0.56063095]


### 30 | Create a 1D array of random integers with size 15. Then, change all values greater than 5 to zero.

In [80]:
v = np.random.randint(0,20,size=15)
v[v > 5] = 0
print(v)


[0 0 3 0 0 0 4 4 3 0 2 0 0 0 4]


### 31 | Subtract the mean of each row of a matrix

In [5]:
v = np.random.rand(5, 10)
y = v - v.mean(axis=1, keepdims=True)
print(y)

[[-0.08944933 -0.28899218 -0.03702168  0.14235215 -0.17981964  0.27788168
   0.21782724  0.42213169 -0.39742704 -0.06748289]
 [-0.37267471 -0.26834836  0.09190463  0.29470254 -0.50494545  0.46822142
  -0.2290279   0.49012977  0.35127039 -0.32123233]
 [ 0.29175944 -0.18171305 -0.10340778 -0.07573363 -0.03517839 -0.07478394
  -0.32449966 -0.21924942  0.09595453  0.6268519 ]
 [-0.08415046  0.18588739 -0.2735782   0.01114907 -0.23333195 -0.16411561
   0.32506618  0.05135257 -0.1363594   0.3180804 ]
 [-0.08244233  0.19148984 -0.47949222  0.14316981 -0.17769598  0.32144914
  -0.020619    0.04545357 -0.24172146  0.30040863]]


### 32 | How to I sort an array by the nth column?

In [14]:
m = np.random.randint(0,30,size=(3,3))
print(np.sort(m[:,1]))

[ 1  6 12]


### 33 | How to tell if a given 2D array has null columns?

In [15]:
v = np.random.randint(0,3,(3,10))
print((~v.any(axis=0)).any())

False


### 34 | How to swap two rows of an array?

In [21]:
v = np.arange(25).reshape(5,5)
v[[0,1]]=v[[1,0]]
print(v)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 35 | Create a 1D array with values [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] and select elements from index 3 to 6

In [24]:
v = np.arange(10)
s = v[3:7]
print(s)

[3 4 5 6]


### 36 |  Reverse the array [10, 20, 30, 40, 50] using slicing

In [26]:
v = np.array([10,20,30,40,50])
print(v[::-1])

[50 40 30 20 10]


### 37   Create a 3×4 array and extract columns 2 and 3 as a submatrix using slicing

In [28]:
m = np.random.randint(0,20,size=(3,4))
m = m[:,2:4]
print(m)

[[ 6  8]
 [ 1 18]
 [ 2 14]]


### 38 | From a 4×4 array, select rows with odd indices

In [36]:
m = np.random.randint(0,20,size=(4,4))
print(m[1::2,:])

[[13 14 10  6]
 [ 9 16 19  8]]


### 39 | In a 5×5 2D array, extract the submatrix that includes rows 1 to 3 and columns 2 to 4

In [53]:
m = np.random.randint(0,30,size=(2,5,5))
print(m[:,1:4,2:5])


[[[24  3 15]
  [12 17 24]
  [26  3 15]]

 [[14 21  7]
  [15 17 29]
  [19  2 10]]]


### 40 | Create a 6×6 array and extract the upper triangle elements (above the main diagonal) as a 1D array

In [55]:
m = np.random.randint(0,20,size=(6,6))
print(m[np.triu_indices(6,k=1)])

[ 6 15 10  7 17 16  8  3 11 18  2  3 12  1  9]


### 41 | Create a 1D NumPy array with numbers from 5 to 15 and print its data type (dtype).



In [5]:
v = np.array([5,6,7,8,9,10,11,12,13,14,15])
v.dtype

dtype('int64')

### 41 | Create a 2D NumPy array of shape 2x4 with any numbers (e.g., numbers from 1 to 8) and print it

In [6]:
m = np.random.randint(1,9,size=(2,4))
print(m)

[[2 8 4 5]
 [2 5 3 2]]


In [9]:
m = np.arange(1,9).reshape(2,4)
print(m)

[[1 2 3 4]
 [5 6 7 8]]


#### 42 | Create a float64 NumPy array with values [1.5, 2.5, 3.5], then add it to an int32 array [1, 2, 3] and observe the output.



In [15]:
m = np.array([1.5, 2.5, 3.5],dtype=np.float64)
v = np.array( [1, 2, 3],dtype=np.int32)
sum = v + m 
print(sum)

[2.5 4.5 6.5]


#### 43 | Create a 3D NumPy array of shape (2, 3, 4) with values from 0 to 23.Then, print the element at: second block, third row, second column.



In [21]:
t = np.arange(1,25).reshape(2,3,4)
print(t[1,2,1])

22


### 44 | Print the first column of every row in each block

In [22]:
print(t[:,:,0])

[[ 1  5  9]
 [13 17 21]]


### 45 | Print the second column of every row in each block, preserving the third dimension

In [25]:
print(t[:,:,0:1])

[[[ 1]
  [ 5]
  [ 9]]

 [[13]
  [17]
  [21]]]


### 46 | Print the last row of each block

In [32]:
print(t[:,-1,:])

[[ 9 10 11 12]
 [21 22 23 24]]


### 47 | Print the last row of each block while preserving the second dimensio

In [33]:
print(t[:,-1:,:])

[[[ 9 10 11 12]]

 [[21 22 23 24]]]


### 48 | Print the last two columns of each row in each block

In [35]:
print(t[:,:,2:])

[[[ 3  4]
  [ 7  8]
  [11 12]]

 [[15 16]
  [19 20]
  [23 24]]]


### 49 | Print the middle row of each block, preserving the second dimension

In [38]:
print(t[:,1:2,:])

[[[ 5  6  7  8]]

 [[17 18 19 20]]]


### 50 | Print the first two rows and the last two columns of each block

In [47]:
print(t[:,0:2,2:])

[[[ 3  4]
  [ 7  8]]

 [[15 16]
  [19 20]]]


In [49]:
print(t[:,0:2,-2:])

[[[ 3  4]
  [ 7  8]]

 [[15 16]
  [19 20]]]
