In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.1.1


### 1 | Print the numpy version and the configuration

In [3]:
print(np.__version__)

2.1.1


### 2 | Create a null vector of size 10

In [4]:
v = np.zeros(10 , dtype = int)
print(v)

[0 0 0 0 0 0 0 0 0 0]


### 3| Create a null vector of size 10 but the fifth value which is 1

In [5]:
v = np.zeros(10 , dtype = int)
v[4] = 1
print(v)

[0 0 0 0 1 0 0 0 0 0]


### 4 | Create a vector with values ranging from 10 to 49

In [6]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 5 | Reverse a vector (first element becomes last)

In [7]:
v = np.arange(50)
v = v[::-1]
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 5 | Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
m =np.arange(9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 6 | Find indices of nonzero elements from [1,2,0,0,4,0]


In [9]:
v = np.nonzero([1,2,0,0,4,0])
print(v)

(array([0, 1, 4]),)


### 7 | Create a 3x3 `identity` matrix

#### ماتریس هویت / Identity Matrix

ماتریس هویت یک ماتریس مربعی است که در آن عناصر قطری برابر با ۱ و بقیه عناصر برابر با ۰ هستند، و در ضرب با هر ماتریس دیگری نتیجه همان ماتریس را می‌دهد.

An identity matrix is a square matrix in which all the diagonal elements are 1 and all other elements are 0. It leaves other matrices unchanged when multiplied by them.


In [10]:
m = np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 8 | Create a 3x3x3 array with random values

In [11]:
m = np.random.randint(0,10,size=(3,3,3))
print(m)

[[[9 8 2]
  [8 2 6]
  [3 4 7]]

 [[1 8 7]
  [6 1 3]
  [9 6 4]]

 [[4 2 7]
  [1 9 7]
  [7 7 0]]]


In [12]:
m = np.random.random(size=(3,3,3))
print(m)

[[[0.08165553 0.49906003 0.94536052]
  [0.39194214 0.18328114 0.59898271]
  [0.98745787 0.82870623 0.679962  ]]

 [[0.28939817 0.10134511 0.78960572]
  [0.94692169 0.15663089 0.80193374]
  [0.54841197 0.49571138 0.17660575]]

 [[0.97014158 0.11482202 0.9340606 ]
  [0.82056224 0.43266534 0.57703589]
  [0.42713412 0.40901362 0.8191184 ]]]


### 9 | Create a 10x10 array with random values and find the minimum and maximum values


In [13]:
m = np.random.random(size=(10,10))
max_value , min_value = np.max(m) , np.min(m)
print(max_value,min_value)

0.9972736391830037 0.004596211606997858


In [14]:
m = np.random.random(size=(10,10))
max_value , min_value = m.max(),m.min()
print(max_value,min_value)

0.9986174719183538 0.006439764271886195


In [15]:
m = np.random.randint(0,5,size=(10,10))
print(m)

[[0 3 0 3 3 0 1 3 3 3]
 [4 1 2 0 2 4 2 0 4 4]
 [0 1 1 3 3 3 2 3 0 4]
 [3 3 3 1 1 2 0 0 0 0]
 [4 3 3 2 4 1 0 3 1 1]
 [0 3 3 4 2 4 1 0 3 3]
 [2 0 4 3 3 2 1 0 1 0]
 [2 2 0 3 4 2 1 3 0 2]
 [4 4 3 3 3 4 0 2 3 2]
 [1 0 0 4 4 1 0 0 1 2]]


### 10 | Create a random vector of size 30 and find the mean value

In [16]:
v = np.random.randint(0,10 , size=(30))
v = v.mean()
print(v)

4.5


### 11 | Create a 2d array with 1 on the border and 0 inside

In [17]:
m = np.ones((10,10),dtype=int)
m[1:-1,1:-1] = 0
print(m)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### 12 | What is the result of the following expression?

In [18]:
m = np.diag(1 + np.arange(4), k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 13 | Create a 8x8 matrix and fill it with a checkerboard pattern

In [19]:
m = np.zeros((8,8),dtype=int)
m[1::2,::2]=1 
m[::2,1::2]=1
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 14 | Create a checkerboard 8x8 matrix using the tile function

In [20]:
m = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 15 | Normalize a 5x5 random matrix

In [21]:
m = np.random.random((5,5))
minValue,maxValue = m.min(),m.max()
normalize = (m-minValue)/(maxValue-minValue)
print(normalize)

[[1.         0.38779555 0.85306173 0.4762347  0.77492388]
 [0.57456929 0.06070679 0.02293869 0.76240814 0.        ]
 [0.11478374 0.36181174 0.35045192 0.9434059  0.21727891]
 [0.77595186 0.44107878 0.98001286 0.71456732 0.21523131]
 [0.35154241 0.6171428  0.12405325 0.74114981 0.3964753 ]]


### 16 | Create a custom dtype that describes a color as four unisgned bytes (RGBA)

In [22]:
color = np.dtype([("r", np.ubyte, 1),
("g", np.ubyte, 1),
("b", np.ubyte, 1),
("a", np.ubyte, 1)])

### 17 | Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [23]:
m = np.dot(np.ones((5,3),dtype=int),np.ones((3,2),dtype=int))
print(m)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [24]:
np.ones((5,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### 18 | Given a 1D array, negate all elements which are between 3 and 8, in place

In [25]:
m = np.arange(11)
m[(3<m)&(m<=8)] *= -1
print(m)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


### 19 | Create a 5x5 matrix with row values ranging from 0 to 4

In [26]:
Z = np.zeros((5,5),dtype=int)
Z += np.arange(5)
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 20 | Consider a generator function that generates 10 integers and use it to build an array

In [27]:
def generat ():
    for x in range(10):
        yield x
v = np.fromiter(generat(),dtype=int,count=-1)
print(v)

[0 1 2 3 4 5 6 7 8 9]


### 21 | Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [28]:
v = np.linspace(0,1,10 , endpoint=False)[1:]
print(v)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


### 21 | Create a random vector of size 10 and sort it

In [29]:
v = np.random.permutation(10)
v = np.sort(v)
print(v)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
v = np.random.permutation(10)
v = np.sort(v)[::-1]
print(v)

[9 8 7 6 5 4 3 2 1 0]


### 22 | Create a 30-element array of random integers in the range [1, 100]. Then, sum it using a method faster than np.sum() and print the result.

In [31]:
v = np.random.randint(0,100,size=30)
v = np.add.reduce(v)
print(v)

1577


### 23 | Consider two random array A anb B, check if they are equal

In [32]:
a = np.random.randint(0,20,size=30)
b = np.random.randint(0,20,size=30)
print(np.array_equal(a,b))

False


### 24 | Consider two random arrays, A and B, both with floating-point values. Check if they are equal

In [33]:
a = np.random.uniform(0,10,size=20)
b = np.random.uniform(0,10,size=20)
print(np.allclose(a,b))

False


### 25 | Make an array immutable (readonly)

In [34]:
v = np.arange(0,20)
v.flags.writeable = False
# v[0]=1

### 26 | Create random vector of size 10 and replace the maximum value by 0

In [35]:
v = np.random.randint(0,50,size=10)
v[v.argmax()] = 0
print(v)

[33  0  3 18 32 13  3 18 24  8]


### 27 | How to find the closest value (to a given scalar) in an array?

In [36]:
v = np.array([1, 4, 7, 9, 13, 20])
c = 6
z = v[np.abs(v-c).argmin()]
print(z)

7


### 28 | How to convert a float (32 bits) array into an integer (32 bits) in place?

In [37]:
v = np.arange(10, dtype=np.int32)
v = v.astype(np.float32, copy=False)

### 29 | Create a 5x5 2D array of random numbers between 0 and 1. Then, calculate the mean of each row and store it in a new array.

In [38]:
v = np.random.rand(5, 5)
row_means = np.mean(v, axis=1)
print(row_means)

[0.39900424 0.5206611  0.56842295 0.36413147 0.57250357]


### 30 | Create a 1D array of random integers with size 15. Then, change all values greater than 5 to zero.

In [39]:
v = np.random.randint(0,20,size=15)
v[v > 5] = 0
print(v)


[0 0 0 1 5 0 0 0 0 0 0 0 0 0 0]


### 31 | Subtract the mean of each row of a matrix

In [40]:
v = np.random.rand(5, 10)
y = v - v.mean(axis=1, keepdims=True)
print(y)

[[ 0.19459154 -0.38249523  0.17091303  0.07794803 -0.29521009 -0.54675664
   0.41573842  0.2179859   0.08259977  0.06468526]
 [-0.16662955 -0.33808568 -0.32601559  0.18691596  0.17163556  0.50105725
  -0.40799631  0.52029231  0.16972494 -0.3108989 ]
 [-0.38079888 -0.24571236  0.25397319  0.21102616 -0.1760601  -0.12576205
  -0.03927489 -0.13388105  0.36673046  0.26975952]
 [-0.22625735  0.31240096  0.52707327  0.53325591 -0.38829479  0.07080485
  -0.0926599  -0.24639018 -0.30532397 -0.1846088 ]
 [-0.13882486  0.10208704  0.0851277  -0.26887697  0.2348437   0.5267851
  -0.33194494  0.14398611 -0.12028556 -0.23289732]]


### 32 | How to I sort an array by the nth column?

In [41]:
m = np.random.randint(0,30,size=(3,3))
print(np.sort(m[:,1]))

[15 15 29]


### 33 | How to tell if a given 2D array has null columns?

In [42]:
v = np.random.randint(0,3,(3,10))
print((~v.any(axis=0)).any())

False


### 34 | How to swap two rows of an array?

In [43]:
v = np.arange(25).reshape(5,5)
v[[0,1]]=v[[1,0]]
print(v)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 35 | Create a 1D array with values [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] and select elements from index 3 to 6

In [44]:
v = np.arange(10)
s = v[3:7]
print(s)

[3 4 5 6]


### 36 |  Reverse the array [10, 20, 30, 40, 50] using slicing

In [45]:
v = np.array([10,20,30,40,50])
print(v[::-1])

[50 40 30 20 10]


### 37   Create a 3×4 array and extract columns 2 and 3 as a submatrix using slicing

In [46]:
m = np.random.randint(0,20,size=(3,4))
m = m[:,2:4]
print(m)

[[11 18]
 [18 12]
 [12  6]]


### 38 | From a 4×4 array, select rows with odd indices

In [47]:
m = np.random.randint(0,20,size=(4,4))
print(m[1::2,:])

[[ 3  3 12  6]
 [ 8 16 19  0]]


### 39 | In a 5×5 2D array, extract the submatrix that includes rows 1 to 3 and columns 2 to 4

In [48]:
m = np.random.randint(0,30,size=(2,5,5))
print(m[:,1:4,2:5])


[[[14  8 11]
  [20  6 19]
  [ 5  5  7]]

 [[16 22 22]
  [14 12 14]
  [13  5 22]]]


### 40 | Create a 6×6 array and extract the upper triangle elements (above the main diagonal) as a 1D array

In [49]:
m = np.random.randint(0,20,size=(6,6))
print(m[np.triu_indices(6,k=1)])

[ 4 17  9 14  7  0 17  7  9 12 18  7  9 13 17]


### 41 | Create a 1D NumPy array with numbers from 5 to 15 and print its data type (dtype).



In [50]:
v = np.array([5,6,7,8,9,10,11,12,13,14,15])
v.dtype

dtype('int64')

### 41 | Create a 2D NumPy array of shape 2x4 with any numbers (e.g., numbers from 1 to 8) and print it

In [51]:
m = np.random.randint(1,9,size=(2,4))
print(m)

[[1 3 4 3]
 [8 8 1 7]]


In [52]:
m = np.arange(1,9).reshape(2,4)
print(m)

[[1 2 3 4]
 [5 6 7 8]]


#### 42 | Create a float64 NumPy array with values [1.5, 2.5, 3.5], then add it to an int32 array [1, 2, 3] and observe the output.



In [53]:
m = np.array([1.5, 2.5, 3.5],dtype=np.float64)
v = np.array( [1, 2, 3],dtype=np.int32)
sum = v + m 
print(sum)

[2.5 4.5 6.5]


#### 43 | Create a 3D NumPy array of shape (2, 3, 4) with values from 0 to 23.Then, print the element at: second block, third row, second column.



In [54]:
t = np.arange(1,25).reshape(2,3,4)
print(t[1,2,1])

22


### 44 | Print the first column of every row in each block

In [55]:
print(t[:,:,0])

[[ 1  5  9]
 [13 17 21]]


### 45 | Print the second column of every row in each block, preserving the third dimension

In [56]:
print(t[:,:,0:1])

[[[ 1]
  [ 5]
  [ 9]]

 [[13]
  [17]
  [21]]]


### 46 | Print the last row of each block

In [57]:
print(t[:,-1,:])

[[ 9 10 11 12]
 [21 22 23 24]]


### 47 | Print the last row of each block while preserving the second dimensio

In [58]:
print(t[:,-1:,:])

[[[ 9 10 11 12]]

 [[21 22 23 24]]]


### 48 | Print the last two columns of each row in each block

In [59]:
print(t[:,:,2:])

[[[ 3  4]
  [ 7  8]
  [11 12]]

 [[15 16]
  [19 20]
  [23 24]]]


### 49 | Print the middle row of each block, preserving the second dimension

In [60]:
print(t[:,1:2,:])

[[[ 5  6  7  8]]

 [[17 18 19 20]]]


### 50 | Print the first two rows and the last two columns of each block

In [61]:
print(t[:,0:2,2:])

[[[ 3  4]
  [ 7  8]]

 [[15 16]
  [19 20]]]


In [62]:
print(t[:,0:2,-2:])

[[[ 3  4]
  [ 7  8]]

 [[15 16]
  [19 20]]]


### 51 | Select the last row of each block, keeping the shape

In [63]:
print(t[:,-1:,:])

[[[ 9 10 11 12]]

 [[21 22 23 24]]]


### 52 | Select the first two columns of the last two rows in each block

In [64]:
print(t[:,-2:,0:2])

[[[ 5  6]
  [ 9 10]]

 [[17 18]
  [21 22]]]


### 53 | Replace the middle row of each block with -1

In [65]:
t.copy()[:,1:,:] = -1
print(t)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### 54 | Get the second column of every row in each block, but keep the shape

In [66]:
print(t[:,:,1:2])

[[[ 2]
  [ 6]
  [10]]

 [[14]
  [18]
  [22]]]


### 55 |  Select the second and third rows of each block, but keep the shape

In [67]:
print(t[:,1:,:])

[[[ 5  6  7  8]
  [ 9 10 11 12]]

 [[17 18 19 20]
  [21 22 23 24]]]


### 56 | Get the last element of each row in each block

In [68]:
print(t[:,:,-1])

[[ 4  8 12]
 [16 20 24]]


### 57 |  Get the last element of each row in each block, but keep the shape

In [69]:
print(t[:,:,-1:])

[[[ 4]
  [ 8]
  [12]]

 [[16]
  [20]
  [24]]]


### 58 |  Get the last element of each row in each block, but keep the shape

In [70]:
mask = t[:,:,1] > 5
indices = np.where(mask)
filtered_rows = t[indices]
print(filtered_rows)


[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


### 59 | Given the 2D array a,Replace all elements greater than 10 with 10 and print the resulting array.

In [83]:
a = np.array([[5, 12, 7],
              [15, 3, 11],
              [8, 14, 6]])
mask = a > 10
a[mask]= 10
print(a) 

[[ 5 10  7]
 [10  3 10]
 [ 8 10  6]]


In [85]:
b = np.clip(a,a.min(),10)
print(b)

[[ 5 10  7]
 [10  3 10]
 [ 8 10  6]]


#### 60 | Given the 3D array b below,Extract all rows from the second block where the first column value is even, and print these rows.

In [97]:
b = np.array([
    [[2, 5], [7, 8], [4, 1]],
    [[6, 3], [9, 2], [8, 7]],
    [[5, 6], [3, 4], [7, 8]]
])
m =  b[1,:,0] 
mask = m % 2 == 0  
filtered_rows = b[1][mask]
print(filtered_rows)

[[6 3]
 [8 7]]
