In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.1.1


### 1 | Print the numpy version and the configuration

In [8]:
print(np.__version__)

2.1.1


### 2 | Create a null vector of size 10

In [11]:
v = np.zeros(10 , dtype = int)
print(v)

[0 0 0 0 0 0 0 0 0 0]


### 3| Create a null vector of size 10 but the fifth value which is 1

In [15]:
v = np.zeros(10 , dtype = int)
v[4] = 1
print(v)

[0 0 0 0 1 0 0 0 0 0]


### 4 | Create a vector with values ranging from 10 to 49

In [17]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 5 | Reverse a vector (first element becomes last)

In [19]:
v = np.arange(50)
v = v[::-1]
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 5 | Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
m =np.arange(9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 6 | Find indices of nonzero elements from [1,2,0,0,4,0]


In [28]:
v = np.nonzero([1,2,0,0,4,0])
print(v)

(array([0, 1, 4]),)


### 7 | Create a 3x3 `identity` matrix

#### ماتریس هویت / Identity Matrix

ماتریس هویت یک ماتریس مربعی است که در آن عناصر قطری برابر با ۱ و بقیه عناصر برابر با ۰ هستند، و در ضرب با هر ماتریس دیگری نتیجه همان ماتریس را می‌دهد.

An identity matrix is a square matrix in which all the diagonal elements are 1 and all other elements are 0. It leaves other matrices unchanged when multiplied by them.


In [31]:
m = np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 8 | Create a 3x3x3 array with random values

In [35]:
m = np.random.randint(0,10,size=(3,3,3))
print(m)

[[[7 8 7]
  [1 2 9]
  [6 2 4]]

 [[7 6 2]
  [2 4 9]
  [0 5 2]]

 [[7 0 9]
  [6 2 2]
  [6 0 7]]]


In [44]:
m = np.random.random(size=(3,3,3))
print(m)

[[[0.56300174 0.52288917 0.52208425]
  [0.98834099 0.03474792 0.61975835]
  [0.63998551 0.08196252 0.02539554]]

 [[0.15456671 0.37938633 0.87112398]
  [0.04390573 0.98060755 0.73725392]
  [0.79438162 0.78873624 0.0286968 ]]

 [[0.10045527 0.4535612  0.59288303]
  [0.15561462 0.0308305  0.88968165]
  [0.90350678 0.66350269 0.60106208]]]


### 9 | Create a 10x10 array with random values and find the minimum and maximum values


In [45]:
m = np.random.random(size=(10,10))
max_value , min_value = np.max(m) , np.min(m)
print(max_value,min_value)

0.9683873109102804 0.008603108280660354


In [46]:
m = np.random.random(size=(10,10))
max_value , min_value = m.max(),m.min()
print(max_value,min_value)

0.9911025998150966 0.004152219545075053


In [48]:
m = np.random.randint(0,5,size=(10,10))
print(m)

[[3 1 2 0 0 3 4 3 4 2]
 [1 2 1 4 2 4 0 1 3 2]
 [3 0 1 2 0 0 4 4 0 2]
 [4 0 0 4 2 3 4 3 2 0]
 [0 2 1 0 3 4 4 2 2 3]
 [0 1 4 1 2 2 1 0 1 1]
 [1 0 2 2 0 3 4 2 2 3]
 [1 1 0 1 1 4 3 2 3 3]
 [0 4 3 4 2 3 2 2 4 0]
 [3 0 0 0 1 3 1 4 4 4]]


### 10 | Create a random vector of size 30 and find the mean value

In [53]:
v = np.random.randint(0,10 , size=(30))
v = v.mean()
print(v)

4.166666666666667


### 11 | Create a 2d array with 1 on the border and 0 inside

In [10]:
m = np.ones((10,10),dtype=int)
m[1:-1,1:-1] = 0
print(m)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### 12 | What is the result of the following expression?

In [12]:
m = np.diag(1 + np.arange(4), k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 13 | Create a 8x8 matrix and fill it with a checkerboard pattern

In [28]:
m = np.zeros((8,8),dtype=int)
m[1::2,::2]=1 
m[::2,1::2]=1
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 14 | Create a checkerboard 8x8 matrix using the tile function

In [32]:
m = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 15 | Normalize a 5x5 random matrix

In [34]:
m = np.random.random((5,5))
minValue,maxValue = m.min(),m.max()
normalize = (m-minValue)/(maxValue-minValue)
print(normalize)

[[0.03253419 0.59163435 0.92910908 0.70579876 0.28021835]
 [0.59641919 0.27973673 1.         0.28289697 0.27238368]
 [0.03412728 0.39667086 0.86979669 0.15165032 0.        ]
 [0.8318821  0.05332412 0.5525875  0.39865209 0.69245356]
 [0.30006347 0.8717279  0.38893121 0.14300384 0.0222705 ]]


### 16 | Create a custom dtype that describes a color as four unisgned bytes (RGBA)

In [36]:
color = np.dtype([("r", np.ubyte, 1),
("g", np.ubyte, 1),
("b", np.ubyte, 1),
("a", np.ubyte, 1)])

### 17 | Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [39]:
m = np.dot(np.ones((5,3),dtype=int),np.ones((3,2),dtype=int))
print(m)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [40]:
np.ones((5,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### 18 | Given a 1D array, negate all elements which are between 3 and 8, in place

In [55]:
m = np.arange(11)
m[(3<m)&(m<=8)] *= -1
print(m)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


### 19 | What is the output of the following script?

In [56]:
Z = np.zeros((5,5),dtype=int)
Z += np.arange(5)
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
