In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.1.1


### 1 | Print the numpy version and the configuration

In [4]:
print(np.__version__)

2.1.1


### 2 | Create a null vector of size 10

In [5]:
v = np.zeros(10 , dtype = int)
print(v)

[0 0 0 0 0 0 0 0 0 0]


### 3| Create a null vector of size 10 but the fifth value which is 1

In [6]:
v = np.zeros(10 , dtype = int)
v[4] = 1
print(v)

[0 0 0 0 1 0 0 0 0 0]


### 4 | Create a vector with values ranging from 10 to 49

In [7]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 5 | Reverse a vector (first element becomes last)

In [8]:
v = np.arange(50)
v = v[::-1]
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 5 | Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
m =np.arange(9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 6 | Find indices of nonzero elements from [1,2,0,0,4,0]


In [10]:
v = np.nonzero([1,2,0,0,4,0])
print(v)

(array([0, 1, 4]),)


### 7 | Create a 3x3 `identity` matrix

#### ماتریس هویت / Identity Matrix

ماتریس هویت یک ماتریس مربعی است که در آن عناصر قطری برابر با ۱ و بقیه عناصر برابر با ۰ هستند، و در ضرب با هر ماتریس دیگری نتیجه همان ماتریس را می‌دهد.

An identity matrix is a square matrix in which all the diagonal elements are 1 and all other elements are 0. It leaves other matrices unchanged when multiplied by them.


In [11]:
m = np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 8 | Create a 3x3x3 array with random values

In [12]:
m = np.random.randint(0,10,size=(3,3,3))
print(m)

[[[6 2 6]
  [2 3 3]
  [1 3 4]]

 [[0 1 3]
  [3 5 4]
  [8 5 9]]

 [[1 7 7]
  [1 0 1]
  [5 6 4]]]


In [13]:
m = np.random.random(size=(3,3,3))
print(m)

[[[0.11672914 0.13134109 0.23733699]
  [0.13491506 0.64149537 0.38668121]
  [0.18839423 0.46479022 0.43092837]]

 [[0.07628562 0.49011083 0.73879574]
  [0.02806956 0.32132712 0.51580519]
  [0.38768623 0.44992767 0.67265891]]

 [[0.49585376 0.87186637 0.37941114]
  [0.18274212 0.28232154 0.32885934]
  [0.14259158 0.43063617 0.05987025]]]


### 9 | Create a 10x10 array with random values and find the minimum and maximum values


In [14]:
m = np.random.random(size=(10,10))
max_value , min_value = np.max(m) , np.min(m)
print(max_value,min_value)

0.9811541299004785 0.023099235547332397


In [15]:
m = np.random.random(size=(10,10))
max_value , min_value = m.max(),m.min()
print(max_value,min_value)

0.9987623482743804 0.016856190587012487


In [16]:
m = np.random.randint(0,5,size=(10,10))
print(m)

[[0 3 3 1 1 4 4 0 0 3]
 [4 4 3 4 0 2 4 2 2 0]
 [3 4 2 3 2 4 3 0 4 0]
 [1 4 3 1 0 4 2 2 1 4]
 [1 0 3 0 3 4 2 4 4 0]
 [1 1 3 3 1 1 3 3 3 1]
 [3 4 3 3 1 1 2 3 1 0]
 [4 2 1 0 2 1 1 2 2 0]
 [4 4 3 4 3 0 1 3 4 2]
 [1 3 4 2 3 3 0 1 4 2]]


### 10 | Create a random vector of size 30 and find the mean value

In [17]:
v = np.random.randint(0,10 , size=(30))
v = v.mean()
print(v)

4.6


### 11 | Create a 2d array with 1 on the border and 0 inside

In [18]:
m = np.ones((10,10),dtype=int)
m[1:-1,1:-1] = 0
print(m)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### 12 | What is the result of the following expression?

In [19]:
m = np.diag(1 + np.arange(4), k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 13 | Create a 8x8 matrix and fill it with a checkerboard pattern

In [20]:
m = np.zeros((8,8),dtype=int)
m[1::2,::2]=1 
m[::2,1::2]=1
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 14 | Create a checkerboard 8x8 matrix using the tile function

In [21]:
m = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 15 | Normalize a 5x5 random matrix

In [22]:
m = np.random.random((5,5))
minValue,maxValue = m.min(),m.max()
normalize = (m-minValue)/(maxValue-minValue)
print(normalize)

[[0.85722544 0.63003519 0.02694206 0.45103215 0.28414636]
 [0.28624228 0.62970014 0.45778453 0.64232786 0.99337104]
 [1.         0.46425905 0.64178837 0.9655573  0.05706563]
 [0.10784099 0.42867142 0.         0.32178929 0.45015252]
 [0.10763598 0.04370444 0.56350263 0.69911747 0.80755543]]


### 16 | Create a custom dtype that describes a color as four unisgned bytes (RGBA)

In [23]:
color = np.dtype([("r", np.ubyte, 1),
("g", np.ubyte, 1),
("b", np.ubyte, 1),
("a", np.ubyte, 1)])

### 17 | Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [24]:
m = np.dot(np.ones((5,3),dtype=int),np.ones((3,2),dtype=int))
print(m)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [25]:
np.ones((5,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### 18 | Given a 1D array, negate all elements which are between 3 and 8, in place

In [26]:
m = np.arange(11)
m[(3<m)&(m<=8)] *= -1
print(m)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


### 19 | Create a 5x5 matrix with row values ranging from 0 to 4

In [27]:
Z = np.zeros((5,5),dtype=int)
Z += np.arange(5)
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 20 | Consider a generator function that generates 10 integers and use it to build an array

In [28]:
def generat ():
    for x in range(10):
        yield x
v = np.fromiter(generat(),dtype=int,count=-1)
print(v)

[0 1 2 3 4 5 6 7 8 9]


### 21 | Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [29]:
v = np.linspace(0,1,10 , endpoint=False)[1:]
print(v)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


### 21 | Create a random vector of size 10 and sort it

In [30]:
v = np.random.permutation(10)
v = np.sort(v)
print(v)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
v = np.random.permutation(10)
v = np.sort(v)[::-1]
print(v)

[9 8 7 6 5 4 3 2 1 0]


### 22 | Create a 30-element array of random integers in the range [1, 100]. Then, sum it using a method faster than np.sum() and print the result.

In [32]:
v = np.random.randint(0,100,size=30)
v = np.add.reduce(v)
print(v)

1258


### 23 | Consider two random array A anb B, check if they are equal

In [33]:
a = np.random.randint(0,20,size=30)
b = np.random.randint(0,20,size=30)
print(np.array_equal(a,b))

False


### 24 | Consider two random arrays, A and B, both with floating-point values. Check if they are equal

In [34]:
a = np.random.uniform(0,10,size=20)
b = np.random.uniform(0,10,size=20)
print(np.allclose(a,b))

False


### 25 | Make an array immutable (readonly)

In [35]:
v = np.arange(0,20)
v.flags.writeable = False
# v[0]=1

### 26 | Create random vector of size 10 and replace the maximum value by 0

In [36]:
v = np.random.randint(0,50,size=10)
v[v.argmax()] = 0
print(v)

[38  7 29 19 11 20 40 28  0 16]


### 27 | How to find the closest value (to a given scalar) in an array?

In [37]:
v = np.array([1, 4, 7, 9, 13, 20])
c = 6
z = v[np.abs(v-c).argmin()]
print(z)

7


### 28 | How to convert a float (32 bits) array into an integer (32 bits) in place?

In [38]:
v = np.arange(10, dtype=np.int32)
v = v.astype(np.float32, copy=False)

### 29 | Create a 5x5 2D array of random numbers between 0 and 1. Then, calculate the mean of each row and store it in a new array.

In [39]:
v = np.random.rand(5, 5)
row_means = np.mean(v, axis=1)
print(row_means)

[0.49289739 0.42813496 0.57226555 0.26376578 0.68686961]


### 30 | Create a 1D array of random integers with size 15. Then, change all values greater than 5 to zero.

In [40]:
v = np.random.randint(0,20,size=15)
v[v > 5] = 0
print(v)


[0 0 1 0 0 0 0 0 0 0 2 0 2 0 0]


### 31 | Subtract the mean of each row of a matrix

In [41]:
v = np.random.rand(5, 10)
y = v - v.mean(axis=1, keepdims=True)
print(y)

[[-0.30945031 -0.34215499  0.59171096  0.1466003  -0.02403273 -0.30564345
  -0.0234575   0.29819585  0.32143056 -0.3531987 ]
 [-0.35237247 -0.17541918  0.19418539  0.16876545  0.00352662  0.26531257
  -0.37443368  0.20745166  0.0741968  -0.01121316]
 [ 0.385744   -0.04687817 -0.36794383  0.42420458  0.0892473   0.29709691
  -0.30385617 -0.37266119 -0.27717343  0.17222001]
 [-0.23297379  0.52648566 -0.02309691 -0.35752704 -0.06833909  0.37883827
  -0.1128747  -0.39905513 -0.11622304  0.40476576]
 [ 0.26020446  0.26480303 -0.22633324 -0.11683503 -0.17972154  0.5116115
  -0.29149631  0.45954918 -0.4035012  -0.27828085]]


### 32 | How to I sort an array by the nth column?

In [42]:
m = np.random.randint(0,30,size=(3,3))
print(np.sort(m[:,1]))

[ 5 13 23]


### 33 | How to tell if a given 2D array has null columns?

In [43]:
v = np.random.randint(0,3,(3,10))
print((~v.any(axis=0)).any())

False


### 34 | How to swap two rows of an array?

In [44]:
v = np.arange(25).reshape(5,5)
v[[0,1]]=v[[1,0]]
print(v)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 35 | Create a 1D array with values [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] and select elements from index 3 to 6

In [45]:
v = np.arange(10)
s = v[3:7]
print(s)

[3 4 5 6]


### 36 |  Reverse the array [10, 20, 30, 40, 50] using slicing

In [46]:
v = np.array([10,20,30,40,50])
print(v[::-1])

[50 40 30 20 10]


### 37   Create a 3×4 array and extract columns 2 and 3 as a submatrix using slicing

In [47]:
m = np.random.randint(0,20,size=(3,4))
m = m[:,2:4]
print(m)

[[ 6  8]
 [ 8  4]
 [11  7]]


### 38 | From a 4×4 array, select rows with odd indices

In [48]:
m = np.random.randint(0,20,size=(4,4))
print(m[1::2,:])

[[13  1  8  0]
 [ 6 16 15  2]]


### 39 | In a 5×5 2D array, extract the submatrix that includes rows 1 to 3 and columns 2 to 4

In [49]:
m = np.random.randint(0,30,size=(2,5,5))
print(m[:,1:4,2:5])


[[[14  5 14]
  [18 19 23]
  [ 4 27 22]]

 [[ 3 27 13]
  [ 9  5 23]
  [10  9 23]]]


### 40 | Create a 6×6 array and extract the upper triangle elements (above the main diagonal) as a 1D array

In [50]:
m = np.random.randint(0,20,size=(6,6))
print(m[np.triu_indices(6,k=1)])

[12  1  9 19  5  0 11  6 13  7  0 18 17 13  8]


### 41 | Create a 1D NumPy array with numbers from 5 to 15 and print its data type (dtype).



In [51]:
v = np.array([5,6,7,8,9,10,11,12,13,14,15])
v.dtype

dtype('int64')

### 41 | Create a 2D NumPy array of shape 2x4 with any numbers (e.g., numbers from 1 to 8) and print it

In [52]:
m = np.random.randint(1,9,size=(2,4))
print(m)

[[3 6 6 1]
 [4 6 2 1]]


In [53]:
m = np.arange(1,9).reshape(2,4)
print(m)

[[1 2 3 4]
 [5 6 7 8]]


#### 42 | Create a float64 NumPy array with values [1.5, 2.5, 3.5], then add it to an int32 array [1, 2, 3] and observe the output.



In [54]:
m = np.array([1.5, 2.5, 3.5],dtype=np.float64)
v = np.array( [1, 2, 3],dtype=np.int32)
sum = v + m 
print(sum)

[2.5 4.5 6.5]


#### 43 | Create a 3D NumPy array of shape (2, 3, 4) with values from 0 to 23.Then, print the element at: second block, third row, second column.



In [55]:
t = np.arange(1,25).reshape(2,3,4)
print(t[1,2,1])

22


### 44 | Print the first column of every row in each block

In [56]:
print(t[:,:,0])

[[ 1  5  9]
 [13 17 21]]


### 45 | Print the second column of every row in each block, preserving the third dimension

In [57]:
print(t[:,:,0:1])

[[[ 1]
  [ 5]
  [ 9]]

 [[13]
  [17]
  [21]]]


### 46 | Print the last row of each block

In [58]:
print(t[:,-1,:])

[[ 9 10 11 12]
 [21 22 23 24]]


### 47 | Print the last row of each block while preserving the second dimensio

In [59]:
print(t[:,-1:,:])

[[[ 9 10 11 12]]

 [[21 22 23 24]]]


### 48 | Print the last two columns of each row in each block

In [60]:
print(t[:,:,2:])

[[[ 3  4]
  [ 7  8]
  [11 12]]

 [[15 16]
  [19 20]
  [23 24]]]


### 49 | Print the middle row of each block, preserving the second dimension

In [61]:
print(t[:,1:2,:])

[[[ 5  6  7  8]]

 [[17 18 19 20]]]


### 50 | Print the first two rows and the last two columns of each block

In [62]:
print(t[:,0:2,2:])

[[[ 3  4]
  [ 7  8]]

 [[15 16]
  [19 20]]]


In [63]:
print(t[:,0:2,-2:])

[[[ 3  4]
  [ 7  8]]

 [[15 16]
  [19 20]]]


### 51 | Select the last row of each block, keeping the shape

In [64]:
print(t[:,-1:,:])

[[[ 9 10 11 12]]

 [[21 22 23 24]]]


### 52 | Select the first two columns of the last two rows in each block

In [65]:
print(t[:,-2:,0:2])

[[[ 5  6]
  [ 9 10]]

 [[17 18]
  [21 22]]]


### 53 | Replace the middle row of each block with -1

In [66]:
t.copy()[:,1:,:] = -1
print(t)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### 54 | Get the second column of every row in each block, but keep the shape

In [67]:
print(t[:,:,1:2])

[[[ 2]
  [ 6]
  [10]]

 [[14]
  [18]
  [22]]]


### 55 |  Select the second and third rows of each block, but keep the shape

In [68]:
print(t[:,1:,:])

[[[ 5  6  7  8]
  [ 9 10 11 12]]

 [[17 18 19 20]
  [21 22 23 24]]]


### 56 | Get the last element of each row in each block

In [69]:
print(t[:,:,-1])

[[ 4  8 12]
 [16 20 24]]


### 57 |  Get the last element of each row in each block, but keep the shape

In [70]:
print(t[:,:,-1:])

[[[ 4]
  [ 8]
  [12]]

 [[16]
  [20]
  [24]]]


### 58 |  Get the last element of each row in each block, but keep the shape

In [71]:
mask = t[:,:,1] > 5
indices = np.where(mask)
filtered_rows = t[indices]
print(filtered_rows)


[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


### 59 | Given the 2D array a,Replace all elements greater than 10 with 10 and print the resulting array.

In [72]:
a = np.array([[5, 12, 7],
              [15, 3, 11],
              [8, 14, 6]])
mask = a > 10
a[mask]= 10
print(a) 

[[ 5 10  7]
 [10  3 10]
 [ 8 10  6]]


In [73]:
b = np.clip(a,a.min(),10)
print(b)

[[ 5 10  7]
 [10  3 10]
 [ 8 10  6]]


#### 60 | Given the 3D array b below,Extract all rows from the second block where the first column value is even, and print these rows.

In [74]:
b = np.array([
    [[2, 5], [7, 8], [4, 1]],
    [[6, 3], [9, 2], [8, 7]],
    [[5, 6], [3, 4], [7, 8]]
])
m =  b[1,:,0] 
mask = m % 2 == 0  
filtered_rows = b[1][mask]
print(filtered_rows)

[[6 3]
 [8 7]]


### 61 | Create a 1D array with numbers 0 to 11 and reshape it into a 2D array with shape (3, 4)

In [75]:
m = np.arange(0,12).reshape(3,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 62 | Create a 3D array with shape (2, 3, 4) and change its axes order to (4, 2, 3) using transpose

In [85]:
m = np.ones((2,3,4),dtype=int)
n = np.transpose(m,(0,2,1))
print(n)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


### 63 | Create a 3D NumPy array with shape (3, 4, 2). Then reshape it into a 2D array with 6 rows and 4 columns

In [87]:
m = np.ones((3,4,2))
reshaped = m.reshape(6,4)
print(reshaped)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 64 | Create a 2D array with shape (4, 5). Then split it into 5 equal vertical sections using the split function

In [95]:
m = np.arange(20).reshape(4, 5)
a,b,c,d,f = np.split(m,5,axis=1)
print(b)


[[ 1]
 [ 6]
 [11]
 [16]]


### 65 | Create a 3D array with shape (2, 3, 4) and then reshape it to (3, 8)

In [99]:
m = np.ones((2,3,4),dtype=int)
n = m.reshape(3,8)
print(n)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


#### 66 | Create a 3D array with shape (2, 4, 5),Then, using reshape and transpose, change its shape so that the output array has shape (5, 2, 4)

In [102]:
m = np.ones((2,4,5),dtype=int)
n = np.transpose(m,(2,0,1))
print(n)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


### 67 | Create a 2D array with shape (6, 9) and split it into 3 equal parts along axis 1 (columns),Print each part

In [107]:
m = np.ones((6,9),dtype=int)
parts = np.split(m, 3, axis=1)
for i, part in enumerate(parts):
    print(f"Part {i+1}:\n", part)

Part 1:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Part 2:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Part 3:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


### 58 | Create a 3D array with shape (3, 4, 5) and reshape it into a 2D array with shape (6, 10)

In [110]:
m = np.ones((3,4,5),dtype=int).reshape(6,10)
print(m)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


##### 59 | Create a 2D array with shape (4, 5) containing values from 1 to 20 , Split it into two arrays: one containing even-indexed rows and the other containing odd-indexed rows

In [118]:
m = np.arange(1,21).reshape(4,5)
even_rows = m[1::2,:]
odd_rows = m[0::2, :]
print(odd_rows)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


#### 60 | Create a 3D array of shape (3, 6, 4), then Swap the second and third axes using transpose Extract every second row from the middle axis (after transpose) Extract every second row from the middle axis (after transpose)

In [122]:
a = np.arange(3 * 6 * 4).reshape(3, 6, 4)
b = np.transpose(a, (0, 2, 1)) 
c = b[:, ::2, :]
d = c.reshape(6, 2, 3)
print(d)

[[[ 0  4  8]
  [12 16 20]]

 [[ 2  6 10]
  [14 18 22]]

 [[24 28 32]
  [36 40 44]]

 [[26 30 34]
  [38 42 46]]

 [[48 52 56]
  [60 64 68]]

 [[50 54 58]
  [62 66 70]]]
